# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-26 21:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('date', models.DateTimeField()),
                ('calories', models.SmallIntegerField()),
                ('distance', models.DecimalField(decimal_places=2, max_digits=5)),
                ('hours', models.SmallIntegerField()),
                ('minutes', models.SmallIntegerField()),
                ('seconds', models.SmallIntegerField()),
                ('heartrate', models.SmallIntegerField()),
                ('peak', models.SmallIntegerField()),
                ('cardio', models.SmallIntegerField()),
                ('fatburn', models.SmallIntegerField()),
            ],
        ),
    ]
